python:
  - 2.7
  - 3.5.1
  - 3.6.1

vtk:
  - 8.0.1

itk:
  - 4.12.1

c_compiler:
  - vs2008           # [win]
  - vs2015           # [win]

cxx_compiler:
  - vs2008           # [win]
  - vs2015           # [win]

pin_run_as_build:
  python:
    max_pin: x.x.x
    min_pin: x.x
  vtk: x.x.x
  itk: x.x.x
