## Program:   VMTK
## Module:    Anaconda Distribution
## Language:  Python
## Date:      May 29, 2017

##   Copyright (c) Richard Izzo, Luca Antiga, David Steinman. All rights reserved.
##   See LICENCE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

## Note: this script was contributed by
##       Richard Izzo (Github @rlizzo)
##       University at Buffalo; The Jacobs Institute

## This file contains the packaging and distribution metadata for packaging
## VMTK via the Continuum Analytics Anaconda Python distribution.
## See https://www.continuum.io/ for distribution info

package:
  name: vmtk
  version: "1.4"

source:
  path: D:\projects\vmtk\vmtk
#  git_url: https://github.com/vmtk/vmtk.git

channels:
  - vmtk

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]
  
requirements:
  build:
    - python
    - future
    - cmake
    - vtk >=7.0
    - itk >=4.10
    - git         
    - numpy
    - h5py
    - cmake >=3.6
    - ninja       # [win]
    - setuptools  # [win]

  run:
    - python
    - future 
    - vtk >=7.0
    - itk >=4.10
    - numpy
    - h5py

about:
  home: www.vmtk.org
  license_file: LICENSE
  summary: "vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details."

extra:
  recipe-maintainers:
    -rlizzo
    -lantiga
