vtk:
  - 8.1.0

python:
  - 3.6
  - 3.5
  - 2.7

c_compiler:
  - vs2008           # [win]
  - vs2015           # [win]
  - vs2015           # [win]

cxx_compiler:
  - vs2008           # [win]
  - vs2015           # [win]
  - vs2015           # [win]
  
zip_keys:            
  - python           
  - c_compiler       # [win]
  - cxx_compiler     # [win]

pin_run_as_build:
  python: x.x

CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk   # [osx]

