package:
  name: vtk
  version: "8.0.1"

source:
  fn: VTK-8.0.1.tar.gz
  url: http://www.vtk.org/files/release/8.0/VTK-8.0.1.tar.gz
  sha1: 7321f22b08b82d9871eca98ad072edbaad55da50

build:
  number: 0
  script_end:
    - BACKEND 
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - future
    - hdf5
    - cmake >=3.6 # [win]
    - git         # [win]
    - future      # [win]
    - ninja       # [win]
    - setuptools  # [win]

  run:
    - python
    - hdf5
    - future

test:
  requires:
    - python
    - numpy
    - pillow
  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga