package:
  name: vtk
  version: 7.1.0

source:
  fn:  VTK-7.1.0.tar.gz
  url: http://www.vtk.org/files/release/7.0/VTK-7.1.0.tar.gz

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - cmake >=3.6
    - git
    - ninja
    - future [py27]

  run:
    - python
    - future [py27]

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga
