package:
  name: vtk
  version: "8.0.1"

source:
  fn: VTK-8.0.1.tar.gz
  url: http://www.vtk.org/files/release/8.0/VTK-8.0.1.tar.gz
  sha1: 7321f22b08b82d9871eca98ad072edbaad55da50

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('cxx') }} # [osx]
    - python  {{ python }}
    - pkgconfig             # [unix]
    - ninja
    - cmake >=3.6 
    - git
    - setuptools           
  host:
    - future
    - python {{ python }}
    - hdf5 

  run:
    - python  {{ python }}
    - future 
    - hdf5
    - numpy
    - pillow

test:
  requires:
    - python {{ python }}
    - numpy
    - pillow
    - future
  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.
extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga
