c_compiler:
  - vs2008           # [win]
  - vs2015           # [win]

cxx_compiler:
  - vs2008           # [win]
  - vs2015           # [win]

CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk   # [osx]

