package:
  name: itk
  version: 4.12.1

source:
  git_rev: v4.12.1
  git_url: https://github.com/Kitware/ITK.git

build:
  number: 0

requirements:
  build:
    - cmake >=3.6
    - git

about:
  home: https://itk.org/
  license: >
     See https://itk.org/ITK/project/license.html for details.
  summary: >
    ITK is an open-source, cross-platform C++ toolkit for segmentation and
    registration.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga
