package:
  name: itk
  version: 4.10.1

source:
  git_rev: v4.10.1
  git_url: https://github.com/Kitware/ITK.git

build:
  number: 0
  features:
    - vc14  # [win]

requirements:
  build:
    - cmake >=3.6
    - git
    - ninja  # [win]

about:
  home: https://itk.org/
  license: >
     See https://itk.org/ITK/project/license.html for details.
  summary: >
    ITK is an open-source, cross-platform C++ toolkit for segmentation and
    registration.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga